[package]
name = "sim86"
version = "0.1.0"
edition = "2021"
rust-version = "1.86"

[dependencies]
bitflags = "2.6.0"

[dev-dependencies]
insta = { version = "1.42.0", features = ["yaml"] }

[profile.dev.package]
insta.opt-level = 3
similar.opt-level = 3
